# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import PIL.ExifTags as module_0
import redistricting as module_1
import matplotlib as module_2
import matplotlib.font_manager as module_3


@pytest.mark.xfail(strict=True)
def test_case_0():
    g_p_s_0 = module_0.GPS.GPSDOP
    dict_0 = {}
    module_1.Redistricting(
        g_p_s_0,
        g_p_s_0,
        g_p_s_0,
        g_p_s_0,
        g_p_s_0,
        dict_0,
        population_key=g_p_s_0,
        w=g_p_s_0,
    )


@pytest.mark.xfail(strict=True)
def test_case_1():
    int_0 = 2161
    module_1.Redistricting(
        int_0,
        int_0,
        int_0,
        int_0,
        int_0,
        int_0,
        w=int_0,
        graph_name=int_0,
        assignment_name=int_0,
    )


@pytest.mark.xfail(strict=True)
def test_case_2():
    none_type_0 = None
    bool_0 = False
    str_0 = "FJ"
    dict_0 = {}
    module_1.Redistricting(
        none_type_0,
        bool_0,
        str_0,
        bool_0,
        bool_0,
        single_updaters=dict_0,
        population_key=none_type_0,
    )


@pytest.mark.xfail(strict=True)
def test_case_3():
    str_0 = "~rls["
    bool_0 = False
    module_1.Redistricting(str_0, bool_0, str_0, str_0, bool_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    bool_0 = True
    module_1.Redistricting(bool_0, bool_0, bool_0, bool_0, bool_0, w=bool_0)


@pytest.mark.xfail(strict=True)
def test_case_5():
    var_0 = module_2.matplotlib_fname()
    int_0 = -1647
    module_1.Redistricting(
        var_0, int_0, var_0, var_0, int_0, h=var_0, w=int_0, graph_name=var_0
    )


@pytest.mark.xfail(strict=True)
def test_case_6():
    module_3.win32FontDirectory()
