# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import scipy.sparse.linalg.interface as module_0
import spec_kmeans as module_1
import scipy.special.sf_error as module_2
import platform as module_3
import http as module_4
import scipy.integrate.lsoda as module_5
import scipy.sparse._sputils as module_6


@pytest.mark.xfail(strict=True)
def test_case_0():
    var_0 = module_0.__dir__()
    module_1.repartition(var_0, var_0, var_0, var_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    var_0 = module_2.__dir__()
    module_1.Radial_Decomposition(var_0, var_0, var_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    var_0 = module_3.python_branch()
    module_1.Radial_Decomposition(var_0, var_0, var_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    h_t_t_p_status_0 = module_4.HTTPStatus.OK
    list_0 = []
    module_1.Radial_Decomposition(h_t_t_p_status_0, h_t_t_p_status_0, list_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    var_0 = module_5.__dir__()
    module_1.Construct_Partition(var_0, var_0, var_0, var_0)


def test_case_5():
    set_0 = set()
    int_0 = module_1.weight(set_0, set_0)
    assert int_0 == 0


@pytest.mark.xfail(strict=True)
def test_case_6():
    module_6.matrix()


@pytest.mark.xfail(strict=True)
def test_case_7():
    none_type_0 = None
    module_1.repartition(none_type_0, none_type_0, none_type_0, none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_8():
    none_type_0 = None
    module_1.Embed_Vertices(none_type_0, none_type_0, none_type_0, none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_9():
    none_type_0 = None
    list_0 = [none_type_0, none_type_0, none_type_0, none_type_0]
    var_0 = module_6.upcast_char(*list_0)
    module_1.Radial_Decomposition(var_0, var_0, list_0)
