# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import main as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    int_0 = 3305
    bool_0 = True
    module_0.grid_graph(int_0, int_0, bool_0, bool_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    str_0 = "W@dD&m5-awVdpz>=;*O"
    bool_0 = False
    str_1 = "zB]=QE|]L.6nb:\t+UO"
    str_2 = "main"
    str_3 = "$YXLm+K"
    list_0 = [str_0, str_2, str_3]
    module_0.triangular_graph(str_0, str_1, bool_0, list_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    str_0 = "^v|NtW>GhFLK,CKGVz?"
    none_type_0 = None
    module_0.triangular_graph(str_0, str_0, none_type_0, none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    str_0 = "e"
    int_0 = -1375
    module_0.grid_graph(str_0, str_0, int_0, str_0)
