# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import networkx.generators.small as module_0
import spec_recom as module_1
import numpy.f2py.symbolic as module_2


@pytest.mark.xfail(strict=True)
def test_case_0():
    var_0 = module_0.desargues_graph()
    dict_0 = module_1.fiedler_cut(var_0, randomize_weights=var_0)
    module_1.repartition(var_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    rel_op_0 = module_2.RelOp.LT
    module_1.fiedler(rel_op_0, normalize_laplacian=rel_op_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    none_type_0 = None
    module_1.fiedler(none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    bool_0 = True
    module_1.fiedler(bool_0, bool_0)


def test_case_4():
    pass


@pytest.mark.xfail(strict=True)
def test_case_5():
    none_type_0 = None
    module_1.repartition(none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_6():
    none_type_0 = None
    module_1.fiedler_cut(none_type_0, randomize_weights=none_type_0)
