# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import main as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    str_0 = "9yB96z\\9p"
    module_0.triangular_graph(str_0, str_0, str_0, str_0)
